/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "myproxy_constants.h"

namespace MyProxy {

const myproxyConstants g_myproxy_constants;

myproxyConstants::myproxyConstants() {
}

} // namespace

