/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef myproxy_CONSTANTS_H
#define myproxy_CONSTANTS_H

#include "myproxy_types.h"

namespace MyProxy {

class myproxyConstants {
 public:
  myproxyConstants();

};

extern const myproxyConstants g_myproxy_constants;

} // namespace

#endif
