/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MyProxy_H
#define MyProxy_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "myproxy_types.h"

namespace MyProxy {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MyProxyIf {
 public:
  virtual ~MyProxyIf() {}

  /**
   * A method definition looks like C code. It has a return type, arguments,
   * and optionally a list of exceptions that it may throw. Note that argument
   * lists and exception lists are specified using the exact same syntax as
   * field lists in struct or exception definitions.
   */
  virtual void ping() = 0;
  virtual void httpget_1(std::string& _return, const std::string& url) = 0;
};

class MyProxyIfFactory {
 public:
  typedef MyProxyIf Handler;

  virtual ~MyProxyIfFactory() {}

  virtual MyProxyIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MyProxyIf* /* handler */) = 0;
};

class MyProxyIfSingletonFactory : virtual public MyProxyIfFactory {
 public:
  MyProxyIfSingletonFactory(const boost::shared_ptr<MyProxyIf>& iface) : iface_(iface) {}
  virtual ~MyProxyIfSingletonFactory() {}

  virtual MyProxyIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MyProxyIf* /* handler */) {}

 protected:
  boost::shared_ptr<MyProxyIf> iface_;
};

class MyProxyNull : virtual public MyProxyIf {
 public:
  virtual ~MyProxyNull() {}
  void ping() {
    return;
  }
  void httpget_1(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};


class MyProxy_ping_args {
 public:

  MyProxy_ping_args(const MyProxy_ping_args&);
  MyProxy_ping_args& operator=(const MyProxy_ping_args&);
  MyProxy_ping_args() {
  }

  virtual ~MyProxy_ping_args() throw();

  bool operator == (const MyProxy_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MyProxy_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MyProxy_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MyProxy_ping_pargs {
 public:


  virtual ~MyProxy_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MyProxy_ping_result {
 public:

  MyProxy_ping_result(const MyProxy_ping_result&);
  MyProxy_ping_result& operator=(const MyProxy_ping_result&);
  MyProxy_ping_result() {
  }

  virtual ~MyProxy_ping_result() throw();

  bool operator == (const MyProxy_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MyProxy_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MyProxy_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MyProxy_ping_presult {
 public:


  virtual ~MyProxy_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MyProxy_httpget_1_args__isset {
  _MyProxy_httpget_1_args__isset() : url(false) {}
  bool url :1;
} _MyProxy_httpget_1_args__isset;

class MyProxy_httpget_1_args {
 public:

  MyProxy_httpget_1_args(const MyProxy_httpget_1_args&);
  MyProxy_httpget_1_args& operator=(const MyProxy_httpget_1_args&);
  MyProxy_httpget_1_args() : url() {
  }

  virtual ~MyProxy_httpget_1_args() throw();
  std::string url;

  _MyProxy_httpget_1_args__isset __isset;

  void __set_url(const std::string& val);

  bool operator == (const MyProxy_httpget_1_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const MyProxy_httpget_1_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MyProxy_httpget_1_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MyProxy_httpget_1_pargs {
 public:


  virtual ~MyProxy_httpget_1_pargs() throw();
  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MyProxy_httpget_1_result__isset {
  _MyProxy_httpget_1_result__isset() : success(false) {}
  bool success :1;
} _MyProxy_httpget_1_result__isset;

class MyProxy_httpget_1_result {
 public:

  MyProxy_httpget_1_result(const MyProxy_httpget_1_result&);
  MyProxy_httpget_1_result& operator=(const MyProxy_httpget_1_result&);
  MyProxy_httpget_1_result() : success() {
  }

  virtual ~MyProxy_httpget_1_result() throw();
  std::string success;

  _MyProxy_httpget_1_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const MyProxy_httpget_1_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MyProxy_httpget_1_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MyProxy_httpget_1_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MyProxy_httpget_1_presult__isset {
  _MyProxy_httpget_1_presult__isset() : success(false) {}
  bool success :1;
} _MyProxy_httpget_1_presult__isset;

class MyProxy_httpget_1_presult {
 public:


  virtual ~MyProxy_httpget_1_presult() throw();
  std::string* success;

  _MyProxy_httpget_1_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MyProxyClient : virtual public MyProxyIf {
 public:
  MyProxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MyProxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void httpget_1(std::string& _return, const std::string& url);
  void send_httpget_1(const std::string& url);
  void recv_httpget_1(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MyProxyProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MyProxyIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MyProxyProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_httpget_1(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MyProxyProcessor(boost::shared_ptr<MyProxyIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &MyProxyProcessor::process_ping;
    processMap_["httpget_1"] = &MyProxyProcessor::process_httpget_1;
  }

  virtual ~MyProxyProcessor() {}
};

class MyProxyProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MyProxyProcessorFactory(const ::boost::shared_ptr< MyProxyIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MyProxyIfFactory > handlerFactory_;
};

class MyProxyMultiface : virtual public MyProxyIf {
 public:
  MyProxyMultiface(std::vector<boost::shared_ptr<MyProxyIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MyProxyMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MyProxyIf> > ifaces_;
  MyProxyMultiface() {}
  void add(boost::shared_ptr<MyProxyIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void httpget_1(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->httpget_1(_return, url);
    }
    ifaces_[i]->httpget_1(_return, url);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MyProxyConcurrentClient : virtual public MyProxyIf {
 public:
  MyProxyConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MyProxyConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void httpget_1(std::string& _return, const std::string& url);
  int32_t send_httpget_1(const std::string& url);
  void recv_httpget_1(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
