#include <stdlib.h>
#include <stdio.h>
#include <rpc/rpc.h> /* always needed */
#include "proxy_rpc.h" /* need this too: msg.h will be generated by rpcgen */

int main(int argc, char* argv[]){
  CLIENT *cl;
  char** result;
  char* url;
  char* server;
  
if (argc < 3) {
    fprintf(stderr, "usage: %s host url\n", argv[0]);
    exit(1);
  }
  /*
   * Save values of command line arguments
   */
  server = argv[1];
  url = argv[2];
  
  /** Create client "handle" used for calling MESSAGEPROG on the
   * server designated on the command line. We tell the RPC package
   * to use the "tcp" protocol when contacting the server.
   */
  cl = clnt_create(server, PROXYRPCPROG, PROXYRPCVERS, "tcp");
  if (cl == NULL) {
    /*
     * Couldn't establish connection with server.
     * Print error message and die.
     */
    clnt_pcreateerror(server);
    exit(1);
  }
  /*
   * Call the remote procedure "printmessage" on the server
   */
  result = httpget_1(&url, cl);
  if (result == NULL) {
    /*
     * An error occurred while calling the server.
     * Print error message and die.
     */
    clnt_perror(cl, server);
    exit(1);
  }
  /*
   * Okay, we successfully called the remote procedure.
   */
  if (*result == 0) {
    /*
     * Server was unable to print our message.
     * Print error message and die.
     */
    fprintf(stderr, "%s: %s couldn’t print your message\n",
	    argv[0], server);
    exit(1);
  }
  /*
   * Printed what we received back.
   */
  printf("%s\n", *result);

  return 0;
}
