/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROXY_RPC_H_RPCGEN
#define _PROXY_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROXYRPCPROG 99
#define PROXYRPCVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HTTPGET 1
extern  char ** httpget_1(char **, CLIENT *);
extern  char ** httpget_1_svc(char **, struct svc_req *);
extern int proxyrpcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HTTPGET 1
extern  char ** httpget_1();
extern  char ** httpget_1_svc();
extern int proxyrpcprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROXY_RPC_H_RPCGEN */
